/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuestionnairesRouteImport } from './routes/questionnaires'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as AssessmentsQuestionnaireRouteImport } from './routes/assessments.questionnaire'
import { Route as AssessmentsResultRouteImport } from './routes/assessments.result'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnairesRoute = QuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AssessmentsRoute,
} as any)
const AssessmentsQuestionnaireRoute =
  AssessmentsQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AssessmentsRoute,
  } as any)
const AssessmentsResultRoute = AssessmentsResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AssessmentsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/questionnaire': typeof AssessmentsQuestionnaireRoute
  '/assessments/result': typeof AssessmentsResultRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/questionnaire': typeof AssessmentsQuestionnaireRoute
  '/assessments/result': typeof AssessmentsResultRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/questionnaires': typeof QuestionnairesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/questionnaire': typeof AssessmentsQuestionnaireRoute
  '/assessments/result': typeof AssessmentsResultRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assessments'
    | '/employees'
    | '/login'
    | '/questionnaires'
    | '/register'
    | '/reports'
    | '/assessments/new'
    | '/assessments/questionnaire'
    | '/assessments/result'
    | '/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assessments'
    | '/employees'
    | '/login'
    | '/questionnaires'
    | '/register'
    | '/reports'
    | '/assessments/new'
    | '/assessments/questionnaire'
    | '/assessments/result'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assessments'
    | '/employees'
    | '/login'
    | '/questionnaires'
    | '/register'
    | '/reports'
    | '/assessments/new'
    | '/assessments/questionnaire'
    | '/assessments/result'
    | '/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  LoginRoute: typeof LoginRoute
  QuestionnairesRoute: typeof QuestionnairesRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaires': {
      id: '/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof QuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/questionnaire': {
      id: '/assessments/questionnaire'
      path: '/questionnaire'
      fullPath: '/assessments/questionnaire'
      preLoaderRoute: typeof AssessmentsQuestionnaireRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/result': {
      id: '/assessments/result'
      path: '/result'
      fullPath: '/assessments/result'
      preLoaderRoute: typeof AssessmentsResultRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  AssessmentsQuestionnaireRoute: typeof AssessmentsQuestionnaireRoute
  AssessmentsResultRoute: typeof AssessmentsResultRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsNewRoute: AssessmentsNewRoute,
  AssessmentsQuestionnaireRoute: AssessmentsQuestionnaireRoute,
  AssessmentsResultRoute: AssessmentsResultRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  LoginRoute: LoginRoute,
  QuestionnairesRoute: QuestionnairesRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
